"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import json
import sys

import dj_database_url
from decouple import Csv, config
from corsheaders.defaults import default_headers, default_methods

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-change-me-in-env",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=Csv(),
)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'bootstrap',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # Antes de SessionMiddleware (sesiones en BD) para que django_session resuelva en private.
    'core.middleware.PostgresSearchPathMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.EmpleadoRolValidationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# La base de datos se configura desde variables de entorno (archivo .env en backend/).
# - USE_LOCAL_DB=True → SQLite (db.sqlite3).
# - DATABASE_URL definido → PostgreSQL (Neon u otro); se usa esta URL y se ignoran valores por defecto.
# Las credenciales de tu .env (DATABASE_URL, etc.) son las que usa Django al arrancar.
USE_LOCAL_DB = config("USE_LOCAL_DB", default=False, cast=bool)
DATABASE_URL = config("DATABASE_URL", default="")

if USE_LOCAL_DB:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
elif DATABASE_URL:
    _db = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=False,
    )
    # Zona horaria de sesión PostgreSQL = horario del negocio (México).
    _opts = dict(_db.get("OPTIONS") or {})
    _opts["options"] = "-c timezone=America/Mexico_City"
    _db["OPTIONS"] = _opts
    # search_path=private,public: ver bootstrap.apps (conexión nueva) y
    # core.middleware.PostgresSearchPathMiddleware (cada petición; necesario con pooler transaccional).
    DATABASES = {"default": _db}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Caché en memoria (por proceso). Agiliza el dashboard admin y reduce round-trips a la BD.
# En varios workers de Gunicorn cada uno tiene su propia caché; para compartir entre procesos usa Redis.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "stylo-locmem",
    }
}

# Segundos que se reutiliza la respuesta de GET /api/admin/dashboard/ (misma fecha local).
ADMIN_DASHBOARD_CACHE_SECONDS = config("ADMIN_DASHBOARD_CACHE_SECONDS", default=60, cast=int)

# GET /api/admin/reportes/?tipo=ventas-* (misma clave por rango; TTL corto).
ADMIN_REPORTE_VENTAS_CACHE_SECONDS = config("ADMIN_REPORTE_VENTAS_CACHE_SECONDS", default=20, cast=int)

# GET /api/perfil/ por usuario (se invalida al actualizar perfil o subir avatar si aplica).
PERFIL_API_CACHE_SECONDS = config("PERFIL_API_CACHE_SECONDS", default=30, cast=int)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "login_anon": config("THROTTLE_LOGIN_ANON", default="20/min"),
        "login_user": config("THROTTLE_LOGIN_USER", default="10/min"),
        "login_2fa_verify": config("THROTTLE_LOGIN_2FA_VERIFY", default="30/min"),
        "login_2fa_resend": config("THROTTLE_LOGIN_2FA_RESEND", default="6/min"),
        "register_anon": config("THROTTLE_REGISTER_ANON", default="12/min"),
        "register_user": config("THROTTLE_REGISTER_USER", default="5/min"),
        "recovery_anon": config("THROTTLE_RECOVERY_ANON", default="12/min"),
        "recovery_email": config("THROTTLE_RECOVERY_EMAIL", default="6/min"),
        "recovery_verify": config("THROTTLE_RECOVERY_VERIFY", default="30/min"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=config("JWT_ACCESS_MINUTES", default=60, cast=int)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=config("JWT_REFRESH_DAYS", default=7, cast=int)
    ),
    "ROTATE_REFRESH_TOKENS": config("JWT_ROTATE_REFRESH", default=True, cast=bool),
    "BLACKLIST_AFTER_ROTATION": config("JWT_BLACKLIST_AFTER_ROTATION", default=True, cast=bool),
    "UPDATE_LAST_LOGIN": False,
}

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="https://localhost:4200,https://127.0.0.1:4200",
    cast=Csv(),
)

# Frontend Angular usa withCredentials=true en HttpClient.
# Sin esta bandera el navegador bloquea requests tras el preflight (OPTIONS).
CORS_ALLOW_CREDENTIALS = True

# Mantener métodos y headers necesarios para JWT/Bearer y JSON.
CORS_ALLOW_METHODS = list(default_methods)
CORS_ALLOW_HEADERS = list(default_headers)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=(
        "http://localhost:4200,http://127.0.0.1:4200,"
        "http://127.0.0.1:8000,http://localhost:8000"
    ),
    cast=Csv(),
)

# Email: Brevo API (HTTPS) y/o SMTP de respaldo.
# En Render plan gratuito el SMTP suele estar bloqueado → usa BREVO_API_KEY (API HTTPS).
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-reply@stylo.local")
BREVO_API_KEY = config("BREVO_API_KEY", default="").strip()
BREVO_API_TIMEOUT_SECONDS = config("BREVO_API_TIMEOUT_SECONDS", default=15, cast=int)
BREVO_FROM_EMAIL = config("BREVO_FROM_EMAIL", default="").strip() or DEFAULT_FROM_EMAIL
BREVO_FROM_NAME = config("BREVO_FROM_NAME", default="Stylo Barber Connect").strip() or "Stylo Barber Connect"

EMAIL_HOST = config("EMAIL_HOST", default="").strip()
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="").strip()
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="").strip()
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=20, cast=int)

EMAIL_SMTP_READY = bool(EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
if EMAIL_SMTP_READY:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Firebase/Google login
FIREBASE_PROJECT_ID = config("FIREBASE_PROJECT_ID", default="")
FIREBASE_WEB_API_KEY = config("FIREBASE_WEB_API_KEY", default="")
if not FIREBASE_PROJECT_ID:
    _firebase_credentials_raw = config("FIREBASE_CREDENTIALS", default="")
    if _firebase_credentials_raw:
        try:
            FIREBASE_PROJECT_ID = str(json.loads(_firebase_credentials_raw).get("project_id", "")).strip()
        except Exception:
            FIREBASE_PROJECT_ID = ""

# Clip (pasarela de pagos)
CLIP_API_BASE_URL = config("CLIP_API_BASE_URL", default="https://api-gw.payclip.com")
CLIP_CHECKOUT_CREATE_PATH = config("CLIP_CHECKOUT_CREATE_PATH", default="/paymentrequest")
CLIP_CHECKOUT_CREATE_URL = config("CLIP_CHECKOUT_CREATE_URL", default="")

# Compatibilidad: permite usar variables *_PRUEBA para entorno sandbox.
CLIP_API_KEY = config("CLIP_API_KEY", default=config("CLIP_API_KEY_PRUEBA", default=""))
CLIP_API_SECRET = config("CLIP_API_SECRET", default=config("CLIP_API_SECRET_PRUEBA", default=""))
CLIP_AUTH_TOKEN = config("CLIP_AUTH_TOKEN", default="")

CLIP_RETURN_SUCCESS_URL = config("CLIP_RETURN_SUCCESS_URL", default="http://localhost:4200/cliente/pagos/exito")
CLIP_RETURN_CANCEL_URL = config("CLIP_RETURN_CANCEL_URL", default="http://localhost:4200/cliente/pagos/cancelado")
CLIP_WEBHOOK_URL = config("CLIP_WEBHOOK_URL", default="http://127.0.0.1:8000/api/pagos/clip/webhook/")
CLIP_WEBHOOK_SECRET = config("CLIP_WEBHOOK_SECRET", default="")
CLIP_WEBHOOK_SIGNATURE_HEADER = config("CLIP_WEBHOOK_SIGNATURE_HEADER", default="X-Clip-Signature")
# Cobro Checkout Transparente (POST /payments). Usar SIEMPRE api-gw: en api.payclip.com/payments
# Cloudflare devuelve 1010 ("browser signature") a clientes servidor (urllib/curl), no es un fallo de credenciales.
CLIP_PAYMENTS_URL = config("CLIP_PAYMENTS_URL", default="https://api-gw.payclip.com/payments")
CLIP_PAYMENTS_URL_ALT = config("CLIP_PAYMENTS_URL_ALT", default="")
# Opcional: User-Agent para llamadas server-side (vacío = UA tipo Chrome en código).
CLIP_HTTP_USER_AGENT = config("CLIP_HTTP_USER_AGENT", default="")
CLIP_API_BASE_URL_ALT = config("CLIP_API_BASE_URL_ALT", default="https://api.payclip.com")
# Alexa Skill (vinculación por código de 4 dígitos)
ALEXA_CODIGO_EXP_MINUTES = config("ALEXA_CODIGO_EXP_MINUTES", default=5, cast=int)
ALEXA_MAX_DIAS_ANTELACION = config("ALEXA_MAX_DIAS_ANTELACION", default=30, cast=int)
ALEXA_INTERNAL_KEY = config("ALEXA_INTERNAL_KEY", default="").strip()

# Desactivar rate limiting en tests (mantener todos los scopes para evitar KeyError)
if "test" in sys.argv or "coverage" in sys.argv:
    REST_FRAMEWORK = REST_FRAMEWORK.copy()
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {}