"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from .admin_views import (
    AdminContenidoLegalDetalleView,
    AdminContenidoLegalView,
    AdminConfiguracionView,
    ClipSolicitar2FAView,
    AdminDashboardView,
    AdminEmpleadoDetalleView,
    AdminEmpleadosView,
    AdminImageUploadView,
    AdminInventarioMovimientosView,
    AdminInventarioSalidasMasivasView,
    AdminMonitoreoBDView,
    AdminReportesView,
    AdminRespaldoDBDescargarView,
    AdminRespaldoDBView,
    AdminLogoUploadView,
    AdminPromocionDetalleView,
    AdminPromocionesView,
    AdminPrediccionVentasView,
    AdminProductoDetalleView,
    AdminProductosView,
    AdminProductoStockView,
    AdminServicioDetalleView,
    AdminServiciosView,
    AdminMarcasView,
    AdminSillaDetalleView,
    AdminSillasView,
)
from .public_views import (
    HealthCheckView,
    PublicContactoView,
    PublicLegalView,
    PublicProductosView,
    PublicServiciosView,
)
from .alexa_views import (
    AlexaCatalogoAgendaView,
    AlexaCitaCrearView,
    AlexaCitaPrevalidarView,
    AlexaCodigoVinculacionView,
    AlexaDisponibilidadDiaView,
    AlexaEstadoVinculacionView,
    AlexaVincularView,
)
from .views import (
    ClienteDashboardStatsView,
    ClipPagoIntentarView,
    CitasView,
    CitaPoliticaPagoView,
    DisponibilidadView,
    PromocionValidarView,
    ClipWebhookView,
    BarberosParaAgendarView,
    ActualizarContrasenaOTPView,
    EmailOrUsernameTokenObtainPairView,
    GoogleLoginView,
    Login2FASolicitarCodigoView,
    Login2FAVerificarView,
    LoginView,
    MeView,
    ClienteComprobanteUploadView,
    PerfilAvatarUploadView,
    Perfil2FAPreferenciaView,
    PerfilCambiarContrasenaView,
    PerfilView,
    PedidosView,
    SecretariaCitasTransferenciasView,
    SecretariaDashboardView,
    RecuperarOTPView,
    ReenviarOTPRecuperacionView,
    ReenviarRegistroOTPView,
    RegisterView,
    VerificarOTPRecuperacionView,
    VerifyRegisterOTPView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/health/', HealthCheckView.as_view(), name='health'),
    path('api/auth/token/', EmailOrUsernameTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/auth/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/me/', MeView.as_view(), name='auth_me'),
    path('api/perfil/', PerfilView.as_view(), name='perfil'),
    path('api/perfil/cambiar-contrasena/', PerfilCambiarContrasenaView.as_view(), name='perfil_cambiar_contrasena'),
    path('api/perfil/upload-avatar/', PerfilAvatarUploadView.as_view(), name='perfil_upload_avatar'),
    path('api/comprobantes/upload/', ClienteComprobanteUploadView.as_view(), name='cliente_comprobante_upload'),
    path('api/perfil/2fa/', Perfil2FAPreferenciaView.as_view(), name='perfil_2fa_preferencia'),
    path('api/dashboard-stats/', ClienteDashboardStatsView.as_view(), name='cliente_dashboard_stats'),
    path('api/citas/', CitasView.as_view(), name='citas'),
    path('api/mis-citas/', CitasView.as_view(), name='mis_citas'),
    path('api/citas/politica-pago/', CitaPoliticaPagoView.as_view(), name='citas_politica_pago'),
    path('api/login/', LoginView.as_view(), name='login'),
    path('api/login/google/', GoogleLoginView.as_view(), name='login_google'),
    path('api/login/2fa/verificar/', Login2FAVerificarView.as_view(), name='login_2fa_verificar'),
    path('api/login/2fa/solicitar-codigo/', Login2FASolicitarCodigoView.as_view(), name='login_2fa_solicitar_codigo'),
    path('api/register/', RegisterView.as_view(), name='register'),
    path('api/register/2fa/verificar/', VerifyRegisterOTPView.as_view(), name='register_2fa_verificar'),
    path('api/verificar-otp/', VerifyRegisterOTPView.as_view(), name='verificar_otp'),
    path('api/reenviar-otp/', ReenviarRegistroOTPView.as_view(), name='reenviar_otp'),
    path('api/recuperar-otp/', RecuperarOTPView.as_view(), name='recuperar_otp'),
    path('api/verificar-otp-recuperacion/', VerificarOTPRecuperacionView.as_view(), name='verificar_otp_recuperacion'),
    path('api/reenviar-otp-recuperacion/', ReenviarOTPRecuperacionView.as_view(), name='reenviar_otp_recuperacion'),
    path('api/actualizar-contrasena-otp/', ActualizarContrasenaOTPView.as_view(), name='actualizar_contrasena_otp'),
    path('api/pagos/clip/intentar/', ClipPagoIntentarView.as_view(), name='pagos_clip_intentar'),
    path('api/pagos/clip/webhook/', ClipWebhookView.as_view(), name='pagos_clip_webhook'),
    path('api/barberos/', BarberosParaAgendarView.as_view(), name='barberos_para_agendar'),
    path('api/disponibilidad/', DisponibilidadView.as_view(), name='disponibilidad_barbero'),
    # Fachada Alexa Skill (no altera contratos del frontend Angular)
    path('api/alexa/estado-vinculacion/', AlexaEstadoVinculacionView.as_view(), name='alexa_estado_vinculacion'),
    path('api/alexa/codigo-vinculacion/', AlexaCodigoVinculacionView.as_view(), name='alexa_codigo_vinculacion'),
    path('api/alexa/vincular/', AlexaVincularView.as_view(), name='alexa_vincular'),
    path('api/alexa/catalogo-agenda/', AlexaCatalogoAgendaView.as_view(), name='alexa_catalogo_agenda'),
    path('api/alexa/disponibilidad-dia/', AlexaDisponibilidadDiaView.as_view(), name='alexa_disponibilidad_dia'),
    path('api/alexa/citas/prevalidar/', AlexaCitaPrevalidarView.as_view(), name='alexa_citas_prevalidar'),
    path('api/alexa/citas/crear/', AlexaCitaCrearView.as_view(), name='alexa_citas_crear'),
    path('api/promociones/validar/', PromocionValidarView.as_view(), name='promocion_validar'),
    path('api/pedidos/', PedidosView.as_view(), name='pedidos'),
    path('api/pedidos/crear/', PedidosView.as_view(), name='pedidos_crear'),
    path('api/secretaria/pedidos/', PedidosView.as_view(), name='secretaria_pedidos'),
    path('api/secretaria/pedidos/<int:pedido_id>/', PedidosView.as_view(), name='secretaria_pedidos_detalle'),
    path('api/secretaria/pedidos/<int:pedido_id>/actualizar/', PedidosView.as_view(), name='secretaria_pedidos_actualizar'),
    path('api/secretaria/pedidos/<int:pedido_id>/seguimiento/', PedidosView.as_view(), name='secretaria_pedidos_seguimiento'),
    path('api/secretaria/dashboard/', SecretariaDashboardView.as_view(), name='secretaria_dashboard'),
    path('api/secretaria/citas/', SecretariaCitasTransferenciasView.as_view(), name='secretaria_citas_transferencias'),
    path('api/secretaria/citas/<int:cita_id>/', SecretariaCitasTransferenciasView.as_view(), name='secretaria_citas_transferencias_detalle'),
    path('api/secretaria/citas/<int:cita_id>/actualizar/', SecretariaCitasTransferenciasView.as_view(), name='secretaria_citas_transferencias_actualizar'),
    path('api/public/servicios/', PublicServiciosView.as_view(), name='public_servicios'),
    path('api/public/servicios/<int:servicio_id>/', PublicServiciosView.as_view(), name='public_servicio_detalle'),
    path('api/public/productos/', PublicProductosView.as_view(), name='public_productos'),
    path('api/public/contacto/', PublicContactoView.as_view(), name='public_contacto'),
    # Alias usado por el front (admin.service) si el primer GET falla.
    path('api/configuracion-publica/', PublicContactoView.as_view(), name='configuracion_publica'),
    path('api/public/legal/', PublicLegalView.as_view(), name='public_legal'),
    path('api/contenido-legal/', PublicLegalView.as_view(), name='public_legal_alias'),
    path('api/admin/configuracion/clip/solicitar-2fa/', ClipSolicitar2FAView.as_view(), name='admin_clip_solicitar_2fa'),
    path('api/admin/configuracion/', AdminConfiguracionView.as_view(), name='admin_configuracion'),
    path('api/admin/dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('api/admin/reportes/', AdminReportesView.as_view(), name='admin_reportes'),
    path('api/admin/prediccion-ventas/', AdminPrediccionVentasView.as_view(), name='admin_prediccion_ventas'),
    path('api/admin/monitoreo-bd/', AdminMonitoreoBDView.as_view(), name='admin_monitoreo_bd'),
    path('api/admin/respaldo-db/', AdminRespaldoDBView.as_view(), name='admin_respaldo_db'),
    path('api/admin/respaldo-db/descargar/<str:archivo>/', AdminRespaldoDBDescargarView.as_view(), name='admin_respaldo_db_descargar'),
    path('api/admin/configuracion/upload-logo/', AdminLogoUploadView.as_view(), name='admin_upload_logo'),
    path('api/admin/upload/', AdminImageUploadView.as_view(), name='admin_upload_image'),
    path('api/admin/empleados/', AdminEmpleadosView.as_view(), name='admin_empleados'),
    path('api/admin/empleados/<int:empleado_id>/', AdminEmpleadoDetalleView.as_view(), name='admin_empleado_detalle'),
    path('api/admin/servicios/', AdminServiciosView.as_view(), name='admin_servicios'),
    path('api/admin/servicios/<int:servicio_id>/', AdminServicioDetalleView.as_view(), name='admin_servicio_detalle'),
    path('api/admin/productos/', AdminProductosView.as_view(), name='admin_productos'),
    path('api/admin/productos/<int:producto_id>/', AdminProductoDetalleView.as_view(), name='admin_producto_detalle'),
    path('api/admin/productos/<int:producto_id>/stock/', AdminProductoStockView.as_view(), name='admin_producto_stock'),
    path('api/admin/inventario/movimientos/', AdminInventarioMovimientosView.as_view(), name='admin_inventario_movimientos'),
    path('api/admin/inventario/salidas-masivas/', AdminInventarioSalidasMasivasView.as_view(), name='admin_inventario_salidas_masivas'),
    path('api/admin/contenido-legal/', AdminContenidoLegalView.as_view(), name='admin_contenido_legal'),
    path('api/admin/contenido-legal/<int:contenido_id>/', AdminContenidoLegalDetalleView.as_view(), name='admin_contenido_legal_detalle'),
    path('api/admin/promociones/', AdminPromocionesView.as_view(), name='admin_promociones'),
    path('api/admin/promociones/<int:promocion_id>/', AdminPromocionDetalleView.as_view(), name='admin_promocion_detalle'),
    path('api/admin/sillas/', AdminSillasView.as_view(), name='admin_sillas'),
    path('api/admin/sillas/<int:silla_id>/', AdminSillaDetalleView.as_view(), name='admin_silla_detalle'),
    path('api/admin/marcas/', AdminMarcasView.as_view(), name='admin_marcas'),
]
