
sonar.projectKey=stylo-barber-frontend
sonar.projectName=Stylo Barber Connect — Frontend Angular
sonar.projectVersion=1.0
sonar.organization=TU_ORG_EN_SONARCLOUD   # <── Reemplaza con tu org de SonarCloud
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=\
  **/node_modules/**, \
  **/dist/**, \
  **/.angular/**, \
  **/coverage/**, \
  **/*.spec.ts, \
  **/*.spec.js, \
  src/favicon.ico, \
  src/styles.css, \
 

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts


sonar.javascript.lcov.reportPaths=coverage/stylo-barber-connect/lcov.info

sonar.eslint.reportPaths=eslint-report.json

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300